codecov:
  allow_coverage_offsets: true

parsers:
  go:
    partials_as_hits: true 

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: false
      linux-1.15-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.15-stable"
      linux-1.15-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.15-nightly"
      linux-1.16-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.16-stable"
      linux-1.16-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.16-nightly"
      linux-1.17-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.17-stable"
      linux-1.17-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "linux-1.17-nightly"
      macos-1.15-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.15-stable"
      macos-1.15-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.15-nightly"
      macos-1.16-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.16-stable"
      macos-1.16-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.16-nightly"
      macos-1.17-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.17-stable"
      macos-1.17-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "macos-1.17-nightly"
      windows-1.15-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.15-stable"
      windows-1.15-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.15-nightly"
      windows-1.16-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.16-stable"
      windows-1.16-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.16-nightly"
      windows-1.17-stable:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.17-stable"
      windows-1.17-nightly:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - "windows-1.17-nightly"
    patch:
      default: false
      linux-1.15-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      linux-1.15-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      linux-1.16-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      linux-1.16-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      linux-1.17-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      linux-1.17-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.15-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.15-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.16-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.16-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.17-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      macos-1.17-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.15-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.15-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.16-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.16-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.17-stable:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
      windows-1.17-nightly:
        only_pulls: true
        target: auto
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
    changes:
      default:
        if_ci_failed: error
        if_not_found: success
        only_pulls: false
        branches:
          - master
        flags:
          - "linux-1.15-stable"
          - "linux-1.15-nightly"
          - "linux-1.16-stable"
          - "linux-1.16-nightly"
          - "linux-1.17-stable"
          - "linux-1.17-nightly"
          - "macos-1.15-stable"
          - "macos-1.15-nightly"
          - "macos-1.16-stable"
          - "macos-1.16-nightly"
          - "macos-1.17-stable"
          - "macos-1.17-nightly"
          - "windows-1.15-stable"
          - "windows-1.15-nightly"
          - "windows-1.16-stable"
          - "windows-1.16-nightly"
          - "windows-1.17-stable"
          - "windows-1.17-nightly"

flags:
  linux-1.15-stable:
    paths:
      - /
    carryforward: true
  linux-1.15-nightly:
    paths:
      - /
    carryforward: true
  linux-1.16-stable:
    paths:
      - /
    carryforward: true
  linux-1.16-nightly:
    paths:
      - /
    carryforward: true
  linux-1.17-stable:
    paths:
      - /
    carryforward: true
  linux-1.17-nightly:
    paths:
      - /
    carryforward: true
  macos-1.15-stable:
    paths:
      - /
    carryforward: true
  macos-1.15-nightly:
    paths:
      - /
    carryforward: true
  macos-1.16-stable:
    paths:
      - /
    carryforward: true
  macos-1.16-nightly:
    paths:
      - /
    carryforward: true
  macos-1.17-stable:
    paths:
      - /
    carryforward: true
  macos-1.17-nightly:
    paths:
      - /
    carryforward: true
  windows-1.15-stable:
    paths:
      - /
    carryforward: true
  windows-1.15-nightly:
    paths:
      - /
    carryforward: true
  windows-1.16-stable:
    paths:
      - /
    carryforward: true
  windows-1.16-nightly:
    paths:
      - /
    carryforward: true
  windows-1.17-stable:
    paths:
      - /
    carryforward: true
  windows-1.17-nightly:
    paths:
      - /
    carryforward: true

comment:
  behavior: default
  require_changes: true

github_checks:
  annotations: true
